# Generated by Django 3.2.4 on 2021-07-14 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_first_name', models.CharField(max_length=255)),
                ('id_last_name', models.CharField(max_length=255)),
                ('id_username', models.CharField(max_length=255)),
                ('id_password', models.CharField(max_length=255)),
                ('create', models.DateTimeField(auto_now_add=True)),
                ('password', models.CharField(max_length=255)),
            ],
        ),
    ]
