# Generated by Django 3.2.4 on 2021-07-17 07:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='users',
            old_name='id_password',
            new_name='id_password1',
        ),
        migrations.RenameField(
            model_name='users',
            old_name='password',
            new_name='id_password2',
        ),
    ]
