# Generated by Django 3.2.4 on 2021-08-04 19:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_auto_20210717_0719'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Users',
        ),
    ]
