# Generated by Django 3.2.4 on 2021-08-23 20:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tasks', '0003_auto_20210820_1924'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='author', to=settings.AUTH_USER_MODEL, verbose_name='Автор'),
        ),
        migrations.AlterField(
            model_name='task',
            name='executer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='executer', to=settings.AUTH_USER_MODEL, verbose_name='Исполнитель'),
        ),
    ]
