# Generated by Django 3.2.4 on 2021-08-18 19:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_auto_20210816_1929'),
        ('statuses', '0002_alter_statuses_name'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Statuses',
            new_name='Status',
        ),
    ]
